version: '3.3'
services:
        web:
          image: rtls-node-image
          build: .
          command: "npm start"
          ports:
             - "4200:4200"
          depends_on:
             - "mongo"
        mongo:
                image: "mongo"
                ports:
                   - "27017:27017"

